export const weatherActionTypes = {
  START_FETCHING_WEATHER_DATA: "START_FETCHING_WEATHER_DATA",
  SUCCESS_FETCHING_WEATHER_DATA: "SUCCESS_FETCHING_WEATHER_DATA",
  FAIL_FETCHING_WEATHER_DATA: "FAIL_FETCHING_WEATHER_DATA",
};
