export const countryListActionTypes = {
  ADD_COUNTRY: "ADD_COUNTRY",
  REMOVE_COUNTRY: "REMOVE_COUNTRY",
  START_FETCHING_COUNTRYlIST_DATA: "START_FETCHING_COUNTRYlIST_DATA",
  SUCCESS_FETCHING_COUNTRYlIST_DATA: "SUCCESS_FETCHING_COUNTRYlIST_DATA",
  FAIL_FETCHING_COUNTRYlIST_DATA: "FAIL_FETCHING_COUNTRYlIST_DATA",
};
